[book]
authors = ["Henry Gressmann"]
language = "en"
title = "mdBook Monochrome"
description = "A clean, monochrome design for mdBook, with a new page layout, typography, and navigation."

[output.html]
sidebar-header-nav = true
git-repository-url = "https://github.com/explodingcamera/mdbook-monochrome"
edit-url-template = "https://github.com/explodingcamera/mdbook-monochrome/edit/main/{path}"
